# Site
repository: samamorgan/samamorgan.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sam Morgan
title: Software Developer
email: sama4mail@gmail.com
website: www.samamorgan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: samamorgan1
github_username: samamorgan
stackoverflow_username: "4881095"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: samamorgan86
linkedin_username: sam-a-morgan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: samamorgan
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: Engineer with a proven track record of organizing user and business needs into scalable, durable, and user-friendly solutions. Heavily focused on pay-it-forward style production code that is clean, maintainable, and modular.
  I am proficient with:
  - <mark>Python</mark> <mark>JavaScript</mark> <mark>C/C++</mark> <mark>Java</mark> <mark>HTML</mark> <mark>CSS</mark>
  - <mark>SQL</mark> <mark>NoSQL</mark>
  - <mark>Windows</mark> <mark>Mac</mark> <mark>Linux</mark>
  - <mark>Git</mark> <mark>GitHub</mark> <mark>Bitbucket</mark>
  - <mark>AWS</mark> <mark>Google Cloud</mark> <mark>Google Apps Script</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Lightmatter, Inc.
        link: lightmatter.com
        sub_title: Senior Software Engineer
        caption: Remote • Feb. 2022 - Feb. 2023
        quote: >
          Senior engineer at a health tech focused software consulting agency leading development of startup client projects and open-source packages.
        description: |
          <mark>Python</mark><mark>Django</mark><mark>Postgres</mark><mark>Typescript</mark><mark>Alpine.js</mark><mark>React</mark><mark>HTMX</mark><mark>Tailwind CSS</mark><mark>Jinja</mark>

          - Continuous contribution and planning for open-source project template, [django-hydra](https://github.com/Lightmatter/django-hydra). Work included refactoring test suite to use Pytest, automating CI/CD with GitHub actions and dependabot, converting existing automations to work on any OS, and innumerable small contributions and bugfixes.
          - Contributed to Farewell Fax, Lightmatter's job board service.
          - Lead engineer for Zest, a telehealth dermatology clinic.
          - Lead engineer for replacement of the Health Tech Nerds application.
          - Author and maintainer for the open-source Python API wrapper welkin-health.
          - Author and maintainer for the open-source Django app django-welkin.
          - Paired with and continuously mentored 3-5 engineers as part of grooming for engineering management position.

      - layout: left
        title: Plugable Technologies
        link: plugable.com
        sub_title: Software Developer
        caption: Remote • Jan. 2014 - Feb. 2022
        quote: >
          Lead developer at an e-commerce startup. Roles included Software Developer, Product Owner, CNC Machinist, Graphic Designer, and Inventory Manager. Started as sixth member of company. Ended as second-most senior employee.
        description: |
          <mark>Python</mark><mark>SQL</mark><mark>AWS</mark><mark>Google Cloud</mark><mark>Google Apps Script</mark><mark>Arduino</mark>

          - Upgraded Plugdebug, company's Python-based debug tool.
          - Created Amazon AWS and MWS automations using Python.
          - Developed mission-critical spreadsheets for pricing, sales, and ad data.
          - Designed and implemented an ESP8266-based physical access control system.
          - Oversight on many SDE intern projects.
          - Translated all existing Python software from Python 2 to 3.

      - layout: left
        title: Discount Divers Supply
        link: discountdivers.com
        sub_title: System Administrator
        caption: Seattle, WA • 2013 - 2014
        quote: >
          Expansive responsibilities as a System Administrator, SCUBA technician, and Sales Associate
        description: |
          - Managed three POS/inventory systems
          - Recommended and implemented hardware upgrades
          - Trained sales staff on use of systems
          - SCUBA Technician: Repaired, certified, and sold SCUBA equipment

      - layout: left
        title: The Computer Shop
        sub_title: Computer Repair Technician
        caption: Renton, WA • 2005 - 2013
        description: |
          - Built, managed, and maintained computer and network systems for offices ranging from 4 – 20 employees
          - Consulted with home-use customers. Recommended and installed upgrades post-consultation

      - layout: left
        title: Fletcher Contracting
        sub_title: Construction Laborer
        caption: Molalla, OR • 2004 - 2005

  - title: Education
    layout: list
    content:
      - layout: center
        title: Western Governors University
        caption: Graduated January 2021
        sub_title: B.S. Software Development

  - title: Certifications
    layout: text
    content: |
      - CIW Advanced HTML5 and CSS3 Specialist
      - CIW User Interface Designer
      - CIW Web Design Professional
      - CIW Web Design Specialist
      - CIW Web Foundations Associate
      - CompTIA A+
      - CompTIA Network+
      - CompTIA Project+
      - ITIL Foundation
      - MTA: Windows OS Fundamentals

  - title: Volunteering
    layout: list
    content:
      - layout: left
        title: Washington Trails Association
        description: |
          I volunteer with the WTA to help build and maintain hiking trails around western Washington.

  - title: A Little More About Me
    layout: text
    content: |
      In my free time, I can most often be found working on my 1920s Craftsman house. The only thing that works in an old house is the owner! I also enjoy hiking, tinkering with electronics, and working on my project cars.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
